### ISSUE TITLE
Problem re-appeared after second boot

### ISSUE THREAD

**Issue by WallyYang** [erpalma/lenovo-throttling-fix#11]
There were several throttling warnings during boot before I installed the script and gone once after the installation. However, those warnings re-appeared after I boot my laptop again, any idea what might be the problem?

My laptop is T480 with i7-8650u
System: Arch Linux
Systemd version: 238

Thanks!

**Comment by erpalma** [comment]
Do you mean these?

`CPU3: Package temperature above threshold, cpu clock throttled (total events = 164)`

Your CPU is throttling even with my script active, but it's doing that at a much higher threshold. Even with the script correctly working, the EC sometimes still reports those events to the kernel, I don't know exactly in which conditions but it happens to me too. You can check with [s-tui](https://github.com/amanusk/s-tui) if the script is working correctly though.

**Comment by WallyYang** [comment]
Yep, I can confirm it's working correctly, I guess Lenovo really failed this generation of ThinkPad. Thank you for your script, I shall close this issue.
