### ISSUE TITLE
python-periphery import error

### ISSUE THREAD

**Issue by sapjunior** [erpalma/lenovo-throttling-fix#17]
In archlinux, 

from **mmio** import MMIO
must be change to 
from **periphery**  import MMIO

**Comment by erpalma** [comment]
`mmio.py` is included with the script now. I removed python-periphery from the dependencies.

**Comment by xcrr** [comment]
I think this is an issue with the PKGBUILD on the AUR. It looks like it hasn't been updated yet to copy mmio.py into the arch package.

@erpalma You probably should update the README too to reflect the removed dependency. It still says the project requires python-periphery.

**Comment by erpalma** [comment]
Thanks for pointing out!

**Comment by sapjunior** [comment]
Thank You for a really quick response. I almost forget to close this issue!
