### ISSUE TITLE
Instruction infelicities

### ISSUE THREAD

**Issue by CottonEaster** [erpalma/lenovo-throttling-fix#2]
The instructions could use

`cd lenovo-throttling-fix`

Also, the `pip install` could perhaps use a `-H`.

**Comment by erpalma** [comment]
Yeah, I've omitted the `cd` command to stop blind copy paste ;)

Isn't `-H` the default behavior for sudo?

**Comment by CottonEaster** [comment]
> Isn't -H the default behavior for sudo?

I don't think so - not on my Mint Cinnamon system, anyway. I get an python warning about how the cache is disabled and that I might want to run `sudo` with the H flag.

**Comment by erpalma** [comment]
Ok thanks!

**Comment by CottonEaster** [comment]
Thanks for making those changes to the documentation. However, you have

> adapter/used on other notebooks too

It should be

> adapted/used on other notebooks too
