### ISSUE TITLE
[improvement] make cTDP configurable

### ISSUE THREAD

**Issue by DEvil0000** [erpalma/lenovo-throttling-fix#26]
If I am correct this is MSR 0x64b.
0 is normal.
1 is the low profile.
2 is the high profile.

see my comment in [my other ticket](https://github.com/erpalma/lenovo-throttling-fix/issues/24#issuecomment-409851402)

**Comment by DEvil0000** [comment]
[This](https://github.com/DEvil0000/lenovo-throttling-fix/tree/improvement/configure_cTDP) might work - can test it on monday.

**Comment by erpalma** [comment]
I guess we should document this new feature well on the readme, which is getting quite long btw! :)

**Comment by wintermute42** [comment]
I just want to mention that this script turned out to be a pretty great
solution and that I, as a user of the script, really appreciate how well it
is documented in the readme :-)
