### ISSUE TITLE
[improvement] Install guide for openSUSE

### ISSUE THREAD

**Issue by brycecordill** [erpalma/lenovo-throttling-fix#34]
Since there isn't an installation guide for openSUSE systems, I have made a list of the required packages and attached them at the bottom.  I don't know if all of the packages are necessary (going off guess and check), but having them all installed worked on my system.
[deps.txt](https://github.com/erpalma/lenovo-throttling-fix/files/2299009/deps.txt)

**Comment by erpalma** [comment]
Is `zypper` the package manager on openSUSE? So `zypper install dep1 dep2...` right?

**Comment by brycecordill** [comment]
Yes, that syntax is correct.
