### ISSUE TITLE
question regarding updates

### ISSUE THREAD

**Issue by wintermute42** [erpalma/lenovo-throttling-fix#41]
Just a short question regarding script updates to a newer version. Is it sufficient to just do a git pull of the script repo and then probably re-run the script? Or do I have to do something else like maybe first stop the service an/or uninstall a previous version of the script?

**Comment by erpalma** [comment]
Hmm right, I should mention it in the readme. The steps are pull, install script, systemctl restart. You should also check for changes/additions in the config file which, by default, is not overwritten.

**Comment by wintermute42** [comment]
ok, thank you

**Comment by erpalma** [comment]
Fixed. Sorry for the delay ;)
