### ISSUE TITLE
Hardened kernel

### ISSUE THREAD

**Issue by tSte** [erpalma/lenovo-throttling-fix#64]
Hey guys, nice tool you've got here, works on my X1C5. I was just playing with it and discovered that this does not work with `linux-hardened` kernel (I am on ArchLinux). Running it with `--debug` will log an error related to `/dev/mem`. Perhaps it would be great to update README...

**Comment by erpalma** [comment]
I guess `linux-hardened` has `CONFIG_DEVMEM=n` right?

**Comment by tSte** [comment]
Looks like it...
I just opened https://github.com/erpalma/lenovo-throttling-fix/pull/65 because it took me some time to find out about this and as a user, I'd like to know about restrictions like these immediately.
